In [4]:
pip install pandas numpy

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.2.3-cp39-cp39-macosx_11_0_arm64.whl (11.3 MB)
     |████████████████████████████████| 11.3 MB 16.3 MB/s eta 0:00:01
Collecting numpy
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 14.0 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)
     |████████████████████████████████| 346 kB 6.1 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)
     |████████████████████████████████| 508 kB 11.2 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/jeong-yujin/Library/Python/3.9/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-2.0.2 pandas-2.2.3 pytz-2024.2 tzdata-2024.2
WARNING: You are using pip version 21.2.4; however, version 24.3.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
import numpy as np

In [17]:
df_1801=pd.read_csv('DWC_KXLCLS_OD_DAY_SEOULGU_SEOULGU_201801.csv',encoding='cp949')
df_1801

,배송년월일,송하인_시명,송하인_시코드,송하인_구명,송하인_구코드,수하인_시명,수하인_시코드,수하인_구명,수하인_구코드,대분류_착지물동량 가구/인테리어,대분류_착지물동량 기타,대분류_착지물동량 도서/음반,대분류_착지물동량 디지털/가전,대분류_착지물동량 생활/건강,대분류_착지물동량 스포츠/레저,대분류_착지물동량 식품,대분류_착지물동량 출산/육아,대분류_착지물동량 패션의류,대분류_착지물동량 패션잡화,대분류_착지물동량 화장품/미용
0,20180101,서울특별시,11,용산구,11170,서울특별시,11,서대문구,11410,0,0,0,0,0,8,0,0,0,0,0
1,20180101,서울특별시,11,관악구,11620,서울특별시,11,구로구,11530,0,0,0,0,0,0,0,0,0,0,0
2,20180101,서울특별시,11,관악구,11620,서울특별시,11,성동구,11200,0,0,0,0,0,0,0,0,0,0,0
3,20180101,서울특별시,11,강남구,11680,서울특별시,11,종로구,11110,0,0,10,0,0,0,0,0,0,16,0
4,20180101,서울특별시,11,강남구,11680,서울특별시,11,중구,11140,0,0,5,0,0,0,0,0,0,85,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17936,20180131,서울특별시,11,중구,11140,서울특별시,11,양천구,11470,8,81,10,12,35,8,33,0,98,33,3
17937,20180131,서울특별시,11,중구,11140,서울특별시,11,강서구,11500,15,105,16,20,62,15,25,4,173,41,8
17938,20180131,서울특별시,11,중구,11140,서울특별시,11,구로구,11530,4,91,14,15,37,6,16,0,110,28,6
17939,20180131,서울특별시,11,중구,11140,서울특별시,11,금천구,11545,7,51,16,13,40,7,5,5,80,30,4
17940,20180131,서울특별시,11,중구,11140,서울특별시,11,영등포구,11560,13,111,30,19,67,6,27,5,129,40,7

In [20]:
df_1801.dtypes

배송년월일                 int64
송하인_시명               object
송하인_시코드               int64
송하인_구명               object
송하인_구코드               int64
수하인_시명               object
수하인_시코드               int64
수하인_구명               object
수하인_구코드               int64
대분류_착지물동량 가구/인테리어     int64
대분류_착지물동량 기타          int64
대분류_착지물동량 도서/음반       int64
대분류_착지물동량 디지털/가전      int64
대분류_착지물동량 생활/건강       int64
대분류_착지물동량 스포츠/레저      int64
대분류_착지물동량 식품          int64
대분류_착지물동량 출산/육아       int64
대분류_착지물동량 패션의류        int64
대분류_착지물동량 패션잡화        int64
대분류_착지물동량 화장품/미용      int64
dtype: object

데이터 병합

In [23]:
import pandas as pd
import glob
import numpy as np
from datetime import datetime

def load_and_merge_data(file_pattern='DWC_KXLCLS_OD_DAY_SEOULGU_SEOULGU_*.csv'): # 파일들을 읽고 병합하는 함수
    all_files = glob.glob(file_pattern)
    df_list = []
    for filename in all_files:
        df = pd.read_csv(filename,encoding='cp949')
        df_list.append(df)
    merged_df = pd.concat(df_list, ignore_index=True)
    merged_df['배송년월일'] = pd.to_datetime(merged_df['배송년월일'], format='%Y%m%d')
    
    return merged_df

def aggregate_daily_logistics(df): #일자별, 출발구-도착구별 총 물동량 집계
    volume_columns = [col for col in df.columns if '대분류_착지물동량' in col]
        # 일자별, 출발구-도착구별 총합 계산
    daily_volume = df.groupby(
        ['배송년월일', '송하인_구명', '수하인_구명']
    )[volume_columns].sum().reset_index()
    daily_volume['총_물동량'] = daily_volume[volume_columns].sum(axis=1)
    
    return daily_volume

def create_adjacency_matrices(daily_volume, unique_districts): #일자별 인접행렬 생성 (GNN용)
    unique_dates = sorted(daily_volume['배송년월일'].unique())
    adj_matrices = {}
    
    for date in unique_dates:
        day_data = daily_volume[daily_volume['배송년월일'] == date]
        
        n = len(unique_districts)
        adj_matrix = np.zeros((n, n))
    
        for _, row in day_data.iterrows():
            i = unique_districts.index(row['송하인_구명'])
            j = unique_districts.index(row['수하인_구명'])
            adj_matrix[i][j] = row['총_물동량']
        
        adj_matrices[date] = adj_matrix
    
    return adj_matrices

def prepare_data_for_analysis(file_pattern='DWC_KXLCLS_OD_DAY_SEOULGU_SEOULGU_*.csv'): # 전체 데이터 준비 프로세스
    merged_df = load_and_merge_data(file_pattern)
    daily_volume = aggregate_daily_logistics(merged_df)
    unique_districts = sorted(list(set(daily_volume['송하인_구명'].unique()) | 
                                 set(daily_volume['수하인_구명'].unique())))
    adj_matrices = create_adjacency_matrices(daily_volume, unique_districts)
    return daily_volume, adj_matrices, unique_districts

In [24]:
# 데이터 준비
daily_volume, adj_matrices, unique_districts = prepare_data_for_analysis()

# 시계열 분석을 위한 피벗 테이블 생성
time_series = daily_volume.pivot_table(
    index='배송년월일',
    values='총_물동량',
    aggfunc='sum'
)

In [25]:
# 데이터 품질 체크
print("결측치 확인:")
print(daily_volume.isnull().sum())

print("\n물동량 기초 통계:")
print(daily_volume['총_물동량'].describe())

# 이상치 확인
for district in unique_districts:
    district_data = daily_volume[
        (daily_volume['송하인_구명'] == district) | 
        (daily_volume['수하인_구명'] == district)
    ]
    print(f"\n{district} 물동량 통계:")
    print(district_data['총_물동량'].describe())

결측치 확인:
배송년월일                0
송하인_구명               0
수하인_구명               0
대분류_착지물동량 가구/인테리어    0
대분류_착지물동량 기타         0
대분류_착지물동량 도서/음반      0
대분류_착지물동량 디지털/가전     0
대분류_착지물동량 생활/건강      0
대분류_착지물동량 스포츠/레저     0
대분류_착지물동량 식품         0
대분류_착지물동량 출산/육아      0
대분류_착지물동량 패션의류       0
대분류_착지물동량 패션잡화       0
대분류_착지물동량 화장품/미용     0
총_물동량                0
dtype: int64

물동량 기초 통계:
count    1.260417e+06
mean     3.535940e+02
std      3.824239e+02
min      0.000000e+00
25%      9.700000e+01
50%      2.630000e+02
75%      4.830000e+02
max      1.908500e+04
Name: 총_물동량, dtype: float64

강남구 물동량 통계:
count    101530.000000
mean        690.816242
std         663.073806
min           0.000000
25%         178.000000
50%         581.000000
75%         974.000000
max       19085.000000
Name: 총_물동량, dtype: float64

강동구 물동량 통계:
count    98537.000000
mean       280.252636
std        262.412920
min          0.000000
25%         87.000000
50%        228.000000
75%        388.000000
max       4435.000000
Name: 총_물동량, dtype: float64

강북구 물동량 통계:
count    95093.000000
mean       178.590517
std        160.716954
min          0.000000
25%         72.000000
50%        150.000000
75%        246.000000
max       2134.000000
Name: 총_물동량, dtype: float64

강서구 물동량 통계:
count    101973.000000
mean        500.625499
std         446.405928
min           0.000000
25%         129.000000
50%         439.000000
75%         702.000000
max       10317.000000
Name: 총_물동량, dtype: float64

관악구 물동량 통계:
count    95450.000000
mean       308.012761
std        324.254523
min          0.000000
25%        102.000000
50%        216.000000
75%        408.000000
max       4662.000000
Name: 총_물동량, dtype: float64

광진구 물동량 통계:
count    97904.000000
mean       283.889678
std        250.089435
min          0.000000
25%         93.000000
50%        246.000000
75%        397.000000
max       4244.000000
Name: 총_물동량, dtype: float64

구로구 물동량 통계:
count    100947.000000
mean        309.221324
std         274.523993
min           0.000000
25%          82.000000
50%         267.000000
75%         435.000000
max        3493.000000
Name: 총_물동량, dtype: float64

금천구 물동량 통계:
count    101125.000000
mean        399.037201
std         404.237232
min           0.000000
25%         109.000000
50%         299.000000
75%         584.000000
max        8433.000000
Name: 총_물동량, dtype: float64

노원구 물동량 통계:
count    98209.000000
mean       273.349500
std        279.512133
min          0.000000
25%         82.000000
50%        207.000000
75%        368.000000
max      10506.000000
Name: 총_물동량, dtype: float64

도봉구 물동량 통계:
count    96569.000000
mean       222.847498
std        191.716479
min          0.000000
25%         80.000000
50%        194.000000
75%        315.000000
max       2262.000000
Name: 총_물동량, dtype: float64

동대문구 물동량 통계:
count    97918.000000
mean       334.530597
std        280.635531
min          0.000000
25%        120.000000
50%        299.000000
75%        477.000000
max       3276.000000
Name: 총_물동량, dtype: float64

동작구 물동량 통계:
count    96320.000000
mean       262.411098
std        247.651733
min          0.000000
25%         96.000000
50%        208.000000
75%        360.000000
max       3572.000000
Name: 총_물동량, dtype: float64

마포구 물동량 통계:
count    99310.000000
mean       444.355976
std        377.939074
min          0.000000
25%        115.250000
50%        399.000000
75%        644.000000
max       5135.000000
Name: 총_물동량, dtype: float64

서대문구 물동량 통계:
count    96872.000000
mean       223.784458
std        202.200975
min          0.000000
25%         87.000000
50%        187.000000
75%        304.000000
max       3043.000000
Name: 총_물동량, dtype: float64

서초구 물동량 통계:
count    101088.000000
mean        409.414223
std         397.389521
min           0.000000
25%         116.000000
50%         328.000000
75%         548.000000
max        6090.000000
Name: 총_물동량, dtype: float64

성동구 물동량 통계:
count    100070.000000
mean        385.490716
std         349.611458
min           0.000000
25%         114.000000
50%         339.000000
75%         549.000000
max       10643.000000
Name: 총_물동량, dtype: float64

성북구 물동량 통계:
count    102145.000000
mean        574.789065
std         598.715069
min           0.000000
25%         142.000000
50%         418.000000
75%         817.000000
max        8217.000000
Name: 총_물동량, dtype: float64

송파구 물동량 통계:
count    100960.000000
mean        466.366937
std         466.894386
min           0.000000
25%         113.750000
50%         366.000000
75%         629.000000
max       10643.000000
Name: 총_물동량, dtype: float64

양천구 물동량 통계:
count    96774.000000
mean       265.254872
std        251.147111
min          0.000000
25%         93.000000
50%        212.000000
75%        365.000000
max       4538.000000
Name: 총_물동량, dtype: float64

영등포구 물동량 통계:
count    98993.000000
mean       362.415363
std        312.980039
min          0.000000
25%        106.000000
50%        319.000000
75%        516.000000
max       5134.000000
Name: 총_물동량, dtype: float64

용산구 물동량 통계:
count    98344.000000
mean       384.937159
std        384.371737
min          0.000000
25%         83.000000
50%        304.000000
75%        559.000000
max       4315.000000
Name: 총_물동량, dtype: float64

은평구 물동량 통계:
count    96721.000000
mean       263.078380
std        254.695879
min          0.000000
25%         93.000000
50%        209.000000
75%        356.000000
max      10414.000000
Name: 총_물동량, dtype: float64

종로구 물동량 통계:
count    96388.000000
mean       218.392787
std        181.528092
min          0.000000
25%         76.000000
50%        197.000000
75%        314.000000
max       3765.000000
Name: 총_물동량, dtype: float64

중구 물동량 통계:
count    100679.000000
mean        323.062943
std         292.200109
min           0.000000
25%          80.000000
50%         279.000000
75%         484.000000
max        6962.000000
Name: 총_물동량, dtype: float64

중랑구 물동량 통계:
count    98883.000000
mean       304.542712
std        266.624122
min          0.000000
25%         74.000000
50%        273.000000
75%        435.000000
max       2702.000000
Name: 총_물동량, dtype: float64

In [26]:
daily_volume.head()

,배송년월일,송하인_구명,수하인_구명,대분류_착지물동량 가구/인테리어,대분류_착지물동량 기타,대분류_착지물동량 도서/음반,대분류_착지물동량 디지털/가전,대분류_착지물동량 생활/건강,대분류_착지물동량 스포츠/레저,대분류_착지물동량 식품,대분류_착지물동량 출산/육아,대분류_착지물동량 패션의류,대분류_착지물동량 패션잡화,대분류_착지물동량 화장품/미용,총_물동량
0,2018-01-01,강남구,강남구,0,7,28,0,10,0,0,0,8,32,0,85
1,2018-01-01,강남구,강동구,0,6,11,0,4,0,0,0,0,11,0,32
2,2018-01-01,강남구,강북구,0,0,7,0,0,0,0,0,0,0,0,7
3,2018-01-01,강남구,강서구,0,5,45,0,5,0,0,0,9,53,0,117
4,2018-01-01,강남구,관악구,0,0,16,0,4,0,0,0,8,14,0,42

In [33]:
daily_volume.to_csv('총물동량.csv', encoding='cp949')

In [28]:
time_series.head()

             총_물동량
배송년월일
2018-01-01    6205
2018-01-02  403669
2018-01-03  294872
2018-01-04  249666
2018-01-05  223450

od_matrix: 출발지-도착지 간 총 물동량 매트릭스
district_timeseries: 시계열 형태의 구별 물동량
district_ranking: 구별 물동량 순위
weekday_pattern: 요일별 물동량 패턴
monthly_trend: 월별 물동량 트렌드
origin_volume: 출발지 기준 일별 물동량
destination_volume: 도착지 기준 일별 물동량

In [29]:
import pandas as pd
import numpy as np

def create_analysis_ready_dataframes(daily_volume):
    """
    다양한 분석용 데이터프레임 생성
    """
    # 1. 일자별 구간별 매트릭스 (Origin-Destination Matrix)
    od_matrix = daily_volume.pivot_table(
        index='송하인_구명',
        columns='수하인_구명',
        values='총_물동량',
        aggfunc='sum'
    )
    
    # 2. 시계열 형태의 구별 총 물동량
    district_timeseries = pd.DataFrame()
    
    # 출발지 기준 물동량
    origin_volume = daily_volume.pivot_table(
        index='배송년월일',
        columns='송하인_구명',
        values='총_물동량',
        aggfunc='sum',
        fill_value=0
    )
    district_timeseries['출발_물동량'] = origin_volume.sum(axis=1)
    
    # 도착지 기준 물동량
    destination_volume = daily_volume.pivot_table(
        index='배송년월일',
        columns='수하인_구명',
        values='총_물동량',
        aggfunc='sum',
        fill_value=0
    )
    district_timeseries['도착_물동량'] = destination_volume.sum(axis=1)
    
    # 3. 구별 물동량 순위
    district_ranking = pd.DataFrame({
        '출발_총물동량': daily_volume.groupby('송하인_구명')['총_물동량'].sum(),
        '도착_총물동량': daily_volume.groupby('수하인_구명')['총_물동량'].sum()
    }).round(2)
    
    district_ranking['총_물동량'] = district_ranking['출발_총물동량'] + district_ranking['도착_총물동량']
    district_ranking = district_ranking.sort_values('총_물동량', ascending=False)
    
    # 4. 요일별 물동량 패턴
    daily_volume['요일'] = daily_volume['배송년월일'].dt.day_name()
    weekday_pattern = daily_volume.pivot_table(
        index='요일',
        values='총_물동량',
        aggfunc=['mean', 'std', 'count']
    )
    
    # 5. 월별 물동량 트렌드
    monthly_trend = daily_volume.set_index('배송년월일')['총_물동량'].resample('M').sum()
    
    return {
        'od_matrix': od_matrix,
        'district_timeseries': district_timeseries,
        'district_ranking': district_ranking,
        'weekday_pattern': weekday_pattern,
        'monthly_trend': monthly_trend,
        'origin_volume': origin_volume,
        'destination_volume': destination_volume
    }

def get_district_flow_analysis(daily_volume, district_name):
    """
    특정 구의 물동량 흐름 상세 분석
    """
    # 해당 구의 출발 물동량
    outflow = daily_volume[daily_volume['송하인_구명'] == district_name].copy()
    outflow_summary = outflow.groupby('수하인_구명')['총_물동량'].agg(['sum', 'mean', 'std']).round(2)
    
    # 해당 구의 도착 물동량
    inflow = daily_volume[daily_volume['수하인_구명'] == district_name].copy()
    inflow_summary = inflow.groupby('송하인_구명')['총_물동량'].agg(['sum', 'mean', 'std']).round(2)
    
    return {
        'outflow_summary': outflow_summary.sort_values('sum', ascending=False),
        'inflow_summary': inflow_summary.sort_values('sum', ascending=False)
    }

# 사용 예시
def print_data_summary(daily_volume):
    """
    데이터 요약 정보 출력
    """
    print("=== 데이터 기본 정보 ===")
    print(f"기간: {daily_volume['배송년월일'].min()} ~ {daily_volume['배송년월일'].max()}")
    print(f"총 레코드 수: {len(daily_volume):,}")
    print("\n=== 데이터프레임 구조 ===")
    print(daily_volume.info())
    
    # 변환된 데이터프레임 생성
    analysis_dfs = create_analysis_ready_dataframes(daily_volume)
    
    print("\n=== 구별 총 물동량 순위 (상위 5개 구) ===")
    print(analysis_dfs['district_ranking'].head())
    
    print("\n=== 월별 물동량 트렌드 (최근 5개월) ===")
    print(analysis_dfs['monthly_trend'].tail())
    
    return analysis_dfs

In [30]:
# 데이터 분석 실행
analysis_results = print_data_summary(daily_volume)

# 특정 구의 상세 분석
gangnam_analysis = get_district_flow_analysis(daily_volume, '강남구')
print("\n강남구 물동량 분석:")
print(gangnam_analysis['outflow_summary'].head())

=== 데이터 기본 정보 ===
기간: 2018-01-01 00:00:00 ~ 2023-12-31 00:00:00
총 레코드 수: 1,260,417

=== 데이터프레임 구조 ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260417 entries, 0 to 1260416
Data columns (total 15 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   배송년월일              1260417 non-null  datetime64[ns]
 1   송하인_구명             1260417 non-null  object
 2   수하인_구명             1260417 non-null  object
 3   대분류_착지물동량 가구/인테리어  1260417 non-null  int64
 4   대분류_착지물동량 기타       1260417 non-null  int64
 5   대분류_착지물동량 도서/음반    1260417 non-null  int64
 6   대분류_착지물동량 디지털/가전   1260417 non-null  int64
 7   대분류_착지물동량 생활/건강    1260417 non-null  int64
 8   대분류_착지물동량 스포츠/레저   1260417 non-null  int64
 9   대분류_착지물동량 식품       1260417 non-null  int64
 10  대분류_착지물동량 출산/육아    1260417 non-null  int64
 11  대분류_착지물동량 패션의류     1260417 non-null  int64
 12  대분류_착지물동량 패션잡화     1260417 non-null  int64
 13  대분류_착지물동량 화장품/미용   1260417 non-null  int64
 14  총_물동량              1260417 non-null  int64
dtypes: datetime64[ns](1), int64(12), object(2)
memory usage: 144.2+ MB
None

=== 구별 총 물동량 순위 (상위 5개 구) ===
      출발_총물동량   도착_총물동량     총_물동량
강남구  37575503  37230588  74806091
성북구  41925308  19376013  61301321
강서구  27491738  25657982  53149720
송파구  18489208  30412081  48901289
마포구  24925671  20848705  45774376

=== 월별 물동량 트렌드 (최근 5개월) ===
배송년월일
2023-08-31    4936559
2023-09-30    4836134
2023-10-31    4997009
2023-11-30    5821519
2023-12-31    5588330
Freq: ME, Name: 총_물동량, dtype: int64

강남구 물동량 분석:
            sum     mean      std
수하인_구명
강남구     4667518  2163.89  1733.09
송파구     2746130  1286.24   903.28
서초구     2411277  1123.09   798.65
강서구     1947822   925.77   668.71
마포구     1692963   805.02   576.75

/var/folders/bf/v7jnwl4x1318f88y9y2nlss40000gn/T/ipykernel_57364/609520023.py:57: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_trend = daily_volume.set_index('배송년월일')['총_물동량'].resample('M').sum()